### ISSUE TITLE
Approximate schedule for releasing the code

### ISSUE THREAD

**Issue by YESAndy** [rllab-snu/RNR-Map#1]
Hi,

Thank you for the effort in sharing this work! I wonder if there is a rough schedule (monthly?) for the code release.

**Comment by obin-hero** [comment]
Hello, Thank you for your interest in our work! :)
We are currently organizing the source code to make it simple and easy. 
For now, we plan to release our code on the conference schedule (June).

**Comment by LSK0821** [comment]
> Hello, Thank you for your interest in our work! :) We are currently organizing the source code to make it simple and easy. For now, we plan to release our code on the conference schedule (June).

Looking forward to your project！

**Comment by yanchi-3dv** [comment]
Thank you for sharing your wonderful work!
I found that docs has been released, but jupyter notebook has not been made public yet, I would like to ask if this will be made public in the near future(this or next month).

**Comment by obin-hero** [comment]
For further issues related to code release:
Please contact me through e-mail obin.kwon@rllab.snu.ac.kr

**Comment by whu-lyh** [comment]
any schedule？
